apiVersion: v2
name: postgresql
description: A Helm chart for PostgreSQL with custom values
type: application
version: 0.1.0
appVersion: "15.3.0"  
dependencies:
  - name: postgresql
    version: "12.5.6"  
    repository: "https://charts.bitnami.com/bitnami"
